/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import OBJ.KhachHang;
import OBJ.HoaDon;
import OBJ.NhanVien;
import OBJ.SanPham;
import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.mail.DefaultAuthenticator;
import org.apache.commons.mail.Email;
import org.apache.commons.mail.SimpleEmail;

/**
 *
 * @author Administrator
 */
public class frmBanHang extends javax.swing.JPanel {

    SanPham sp = new SanPham();
    ArrayList<HoaDon> listGioHang = new ArrayList<>();
    NumberFormat formatter = new DecimalFormat("###,###");
    KhachHang kh = new KhachHang();
    NhanVien nv = new NhanVien();
    int index;
    double tongTien;
    private DefaultTableModel defaultTableModel;

    /**
     * Creates new form frmBanHang
     */
    public frmBanHang() {
        initComponents();
        getDataKH(loadKH());
        getDataSP(loadSP());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_gioHang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_thanhToan = new javax.swing.JButton();
        lbl_maKH = new javax.swing.JLabel();
        lbl_tenKH = new javax.swing.JLabel();
        lbl_tongTien = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khachhang = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txt_searchKH = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_sanpham = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        txt_searchSP = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_soLuong = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1920, 950));
        setPreferredSize(new java.awt.Dimension(1920, 950));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store-icon.png"))); // NOI18N
        jLabel1.setText("SIÊU THỊ MINI");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Users-Exit-icon.png"))); // NOI18N
        jButton5.setText("Thoát");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 50, 110, 29));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("|");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 80, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1930, 50));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_gioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_gioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_gioHangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_gioHang);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 640, 190));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mã khách hàng:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Họ tên:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Editing-Delete-icon.png"))); // NOI18N
        jButton1.setText("Xóa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coin-us-dollar-icon.png"))); // NOI18N
        jLabel8.setText("Tổng tiền thanh toán:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 190, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("VND.");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 40, 30));

        btn_thanhToan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_thanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cash-icon.png"))); // NOI18N
        btn_thanhToan.setText("Thanh toán");
        btn_thanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thanhToanActionPerformed(evt);
            }
        });
        jPanel4.add(btn_thanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 140, 50));

        lbl_maKH.setText("..................");
        jPanel4.add(lbl_maKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        lbl_tenKH.setText("...............................");
        jPanel4.add(lbl_tenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        lbl_tongTien.setText("......................");
        jPanel4.add(lbl_tongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 100, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("SIÊU THI MINI");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("70, Hoàng Thế Thiện,Phường Sài Đồng");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Long Biên,Hà Nội");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("hotline:0972532403");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("HÓA ĐƠN BÁN HÀNG");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabel7.setText("----------------------------------------------------------------------------------------------------------------------------------");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 660, -1));

        jLabel17.setText("----------------------------------------------------------------------------------------------------------------------------------");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 670, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("CẢM ƠN QUÝ KHÁCH VÀ HẸN GẶP LẠI");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 670, 630));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_khachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khachhangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_khachhang);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 770, 170));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_searchKH.setToolTipText("");
        txt_searchKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchKHActionPerformed(evt);
            }
        });
        jPanel5.add(txt_searchKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 290, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search-icon.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 30, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Nhập mã hoặc tên khách hàng: ");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 200, 50));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 550, 50));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 800, 270));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(102, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_sanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sanphamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_sanpham);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 770, 200));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_searchSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchSPActionPerformed(evt);
            }
        });
        jPanel6.add(txt_searchSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 280, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search-icon.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 40, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Nhập mã hoặc tên SP: ");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 50));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 500, 60));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Thêm vào giỏ hàng");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 150, 60));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Số lượng:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 80, 50));

        txt_soLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_soLuong.setText("0");
        txt_soLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soLuongActionPerformed(evt);
            }
        });
        jPanel3.add(txt_soLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 50, 30));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 800, 330));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp3152222.jpg"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 900));
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<KhachHang> loadKH() {
        frmKhachHang frm = new frmKhachHang();
        frm.loadFile();
        return frm.listKH;
    }

    public ArrayList<SanPham> loadSP() {
        frmSanPham frm = new frmSanPham();
        frm.loadFile();
        return frm.listSP;
    }

    /*
    public void sendmail(String tenSP, double tien, String emailKH) {
        try {
            Email email = new SimpleEmail();

            // Cấu hình thông tin Email Server
            email.setHostName("smtp.googlemail.com");
            email.setSmtpPort(465);
            email.setAuthenticator(new DefaultAuthenticator("hungkhvnh@gmail.com", "hungkhanh123")); //Nhớ nhập đúng với tài khoản thật nhé :))
            // Với gmail cái này là bắt buộc.
            email.setSSLOnConnect(true);
            // Người gửi
            email.setFrom("hungkhvnh@gmail.com", " Siêu Thị Mini");
            // Tiêu đề
            email.setSubject("XIN TRÂN TRỌNG CẢM ƠN QUÝ KHÁCH HÀNG ĐÃ ỦNG HỘ"); //Tiêu đề khi gửi email
            // Nội dung email
            String covert = String.valueOf(emailKH);
            email.setMsg("Cảm ơn bạn đã mua sản phẩm "+tenSP+" với tổng giá tiền " + formatter.format(tien) + "VND."); //Nội dung email bạn muốn gửi.
            // Người nhận
            email.addTo(emailKH); //Đia chỉ email người nhận
            email.send(); //Thực hiện gửi.
            JOptionPane.showMessageDialog(this,"Gửi email thành công ! Vui lòng kiểm tra email !");
        } catch (Exception e) {
            System.out.println("Gửi không thành công !");
        }
    }
     */
    private void getDataKH(ArrayList<KhachHang> listKH) {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã KH");
        defaultTableModel.addColumn("Họ tên KH");
        defaultTableModel.addColumn("Giới tính");
        defaultTableModel.addColumn("Email");
        defaultTableModel.addColumn("SĐT");
        defaultTableModel.addColumn("Địa Chỉ");
        defaultTableModel.addColumn("Trạng Thái");

        for (KhachHang obj : listKH) {
            Vector vector = new Vector();
            vector.add(obj.getMaKhachHang());
            vector.add(obj.getHoTen());
            vector.add(obj.getGioiTinh());
            vector.add(obj.getEmail());
            vector.add(obj.getSoDienThoai());
            vector.add(obj.getDiaChi());
            vector.add(obj.getTrangThai() == 1 ? "Hoạt động" : "Đã khóa");
            defaultTableModel.addRow(vector);
        }
        tbl_khachhang.setModel(defaultTableModel);
    }

    private void getDataSP(ArrayList<SanPham> listSP) {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã SP");
        defaultTableModel.addColumn("Tên SP");
        defaultTableModel.addColumn("Đơn vi tính");
        defaultTableModel.addColumn("Tên NSX");
        defaultTableModel.addColumn("Giá Nhập");
        defaultTableModel.addColumn("Giá Bán");
        defaultTableModel.addColumn("Số Lượng");

        for (SanPham obj : listSP) {
            Vector vector = new Vector();
            vector.add(obj.getMaSanPham());
            vector.add(obj.getTenSp());
            vector.add(obj.getDonViTinh());
            vector.add(obj.getTenNsx());
            vector.add(obj.getGiaNhap());
            vector.add(obj.getGiaBan());
            vector.add(obj.getSoLuong());
            defaultTableModel.addRow(vector);
        }
        tbl_sanpham.setModel(defaultTableModel);
    }

    public void reset() {
        getDataKH(loadKH());
        getDataSP(loadSP());
        loadGioHang(listGioHang);
        lbl_maKH.setText("...............");
        lbl_tenKH.setText("...............");
        tongTien = 0;
        lbl_tongTien.setText("...............");
    }

    public void saveFile() {
        try {
            FileOutputStream fileOutputStream = new FileOutputStream("hoadon.txt",true);
            Writer writer = new OutputStreamWriter(fileOutputStream, "utf-8"); //Khởi tạo
            BufferedWriter bw = new BufferedWriter(writer); //Khởi tạo
            String data = ""; //Tạo một string data bằng rỗng.
            for (int i = 0; i < listGioHang.size(); i++) {
                SanPham sp = new frmBanHang().getSPByCode(listGioHang.get(i).getMaSP());
                String row = ""; //tạo hàng rỗng
                row = row + listGioHang.get(i).getMaHD() + "\t";
                row = row + listGioHang.get(i).getMaNV() + "\t";
                row = row + listGioHang.get(i).getMaKH() + "\t";
                row = row + kh.getHoTen() + "\t";
                row = row + listGioHang.get(i).getMaSP() + "\t";
                row = row + listGioHang.get(i).getSoLuong() + "\t";
                row = row + sp.getTenSp() + "\t";
                row = row + listGioHang.get(i).getDonGia() + "\t";
                row = row + listGioHang.get(i).getThanhTien() + "\t";
                row = row + listGioHang.get(i).getNgayBan() + "\n";
                data += row;
            }
            bw.write(data);
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(frmBanHang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public int soLuongSPTrongListGioHang(String maSP) {
        for (int i = 0; i < listGioHang.size(); i++) {
            if (maSP.equals(listGioHang.get(i).getMaSP())) {
                return listGioHang.get(i).getSoLuong();
            }
        }
        return 0;
    }

    String maSP;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tbl_gioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_gioHangMouseClicked
        // TODO add your handling code here:
        int row = tbl_gioHang.getSelectedRow();
        maSP = tbl_gioHang.getValueAt(row, 0).toString();
    }//GEN-LAST:event_tbl_gioHangMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double tienGiam;
        for (int i = 0; i < listGioHang.size(); i++) {
            if (maSP.equals(listGioHang.get(i).getMaSP())) {
                tienGiam = listGioHang.get(i).getThanhTien();
                listGioHang.remove(i);
                tongTien = tongTien - tienGiam;
                lbl_tongTien.setText(String.valueOf(tongTien));
            }
        }
        loadGioHang(listGioHang);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_thanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thanhToanActionPerformed
        // TODO add your handling code here:
        if (kh.getMaKhachHang() == null || kh.getMaKhachHang().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chon khách hàng trước!");
            return;
        } else {
            Date date = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy-hh-mm-ss");
            SimpleDateFormat sdf2 = new SimpleDateFormat("dd-MM-yyyy");
            String maHD = kh.getMaKhachHang() + "-" + sdf.format(date);
            String tenSP = sp.getTenSp();
            for (int i = 0; i < listGioHang.size(); i++) {
                HoaDon hd = listGioHang.get(i);
                hd.setMaHD(maHD);
                hd.setMaKH(kh.getMaKhachHang());
                hd.setMaNV(frm_signIn.maDN);
                hd.setNgayBan(sdf2.format(date));
                listGioHang.set(i, hd);
            }
            

            JTextField txtSoTien = new JTextField(10);

            JPanel myPanel = new JPanel();
            myPanel.add(Box.createHorizontalStrut(10));
            myPanel.add(new JLabel("Số tiền khách đưa:"));
            myPanel.add(txtSoTien);
            int result = JOptionPane.showConfirmDialog(null, myPanel, "Số tiền khách thanh toán", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                double soTienKhachDua = Double.parseDouble(txtSoTien.getText());
                if (soTienKhachDua < tongTien) {
                    JOptionPane.showMessageDialog(this, "Số tiền khách đưa chưa đủ !");
                    return;
                } else if (soTienKhachDua > tongTien) {
                    JOptionPane.showMessageDialog(this, "Số tiền trả lại cho khách hàng " + (formatter.format(soTienKhachDua - tongTien)));
                }
                saveFile();
                JOptionPane.showMessageDialog(this, "Thanh toán thành công!");
                frmSanPham frmSP = new frmSanPham();
                frmSP.loadFile();
                for (int i = 0; i < listGioHang.size(); i++) {
                    updateSoLuong(listGioHang.get(i).getMaSP(), listGioHang.get(i).getSoLuong(), frmSP.listSP);
                }
                frmSP.saveFile();
                listGioHang = new ArrayList<>();
                //sendmail(sp.getTenSp(), tongTien, kh.getEmail());
                reset();
            }
        }
    }//GEN-LAST:event_btn_thanhToanActionPerformed

    private void tbl_khachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khachhangMouseClicked
        // TODO add your handling code here:

        int row = tbl_khachhang.getSelectedRow();
        String makh = tbl_khachhang.getValueAt(row, 0).toString();
        ArrayList<KhachHang> listKH = loadKH();
        for (int i = 0; i < listKH.size(); i++) {
            if (makh.equals(listKH.get(i).getMaKhachHang())) {
                kh = listKH.get(i);
                index = i;
                break;
            }
        }
        lbl_maKH.setText(kh.getMaKhachHang());
        lbl_tenKH.setText(kh.getHoTen());

    }//GEN-LAST:event_tbl_khachhangMouseClicked

    private void txt_searchKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchKHActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String timKiem = txt_searchKH.getText();

        if (timKiem.equals("")) {
            getDataKH(loadKH());
        } else {
            ArrayList<KhachHang> listTimKiem = new ArrayList<>();
            for (int i = 0; i < loadKH().size(); i++) {
                if (loadKH().get(i).getMaKhachHang().contains(timKiem) || loadKH().get(i).getHoTen().contains(timKiem)) {
                    listTimKiem.add(loadKH().get(i));
                }
            }
            getDataKH(listTimKiem);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbl_sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sanphamMouseClicked
        // TODO add your handling code here:
        int row = tbl_sanpham.getSelectedRow();
        String makh = tbl_sanpham.getValueAt(row, 0).toString();
        ArrayList<SanPham> listSP = loadSP();
        for (int i = 0; i < listSP.size(); i++) {
            if (makh.equals(listSP.get(i).getMaSanPham())) {
                sp = listSP.get(i);
                index = i;
                break;
            }
        }
        txt_soLuong.setText("1");
    }//GEN-LAST:event_tbl_sanphamMouseClicked

    private void txt_searchSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchSPActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String timKiem = txt_searchSP.getText();

        if (timKiem.equals("")) {
            getDataSP(loadSP());
        } else {
            ArrayList<SanPham> listTimKiem = new ArrayList<>();
            for (int i = 0; i < loadSP().size(); i++) {
                if (loadSP().get(i).getMaSanPham().contains(timKiem) || loadSP().get(i).getTenSp().contains(timKiem)) {
                    listTimKiem.add(loadSP().get(i));
                }
            }
            getDataSP(listTimKiem);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int soLuongMua = Integer.parseInt(txt_soLuong.getText());
        if (soLuongMua <= 0) {
            JOptionPane.showMessageDialog(this, "Số lượng sản phẩm phải >0!");
        } else if (soLuongMua + soLuongSPTrongListGioHang(sp.getMaSanPham()) > sp.getSoLuong()) {
            JOptionPane.showMessageDialog(this, "Số lượng sản phẩm lớn hơn số lượng trong kho");

        } else {
            HoaDon hd = new HoaDon();
            hd.setMaSP(sp.getMaSanPham());
            hd.setSoLuong(soLuongMua);
            hd.setDonGia(Double.parseDouble(sp.getGiaBan()));
            hd.setThanhTien(soLuongMua * Integer.parseInt(sp.getGiaBan()));
            if (checkSPExistGioHang(hd.getMaSP(), listGioHang)) {
                HoaDon hoaDon = listGioHang.get(indexMaSPTrungTrongGioHang);
                hoaDon.setSoLuong(Integer.parseInt(txt_soLuong.getText()) + hoaDon.getSoLuong());
                hoaDon.setThanhTien(hoaDon.getDonGia() * hoaDon.getSoLuong());
                listGioHang.set(indexMaSPTrungTrongGioHang, hoaDon);
            } else {
                listGioHang.add(hd);
            }
            loadGioHang(listGioHang);
            JOptionPane.showMessageDialog(this, "Thêm vào giỏ hàng thành công");
            tongTien = 0;
            for (int i = 0; i < listGioHang.size(); i++) {
                tongTien += listGioHang.get(i).getThanhTien();
            }
            lbl_tongTien.setText(formatter.format(tongTien));

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txt_soLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soLuongActionPerformed

    public void updateSoLuong(String maSP, int soLuongMua, ArrayList<SanPham> listSP) {
        for (int i = 0; i < listSP.size(); i++) {
            if (maSP.equals(listSP.get(i).getMaSanPham())) {
                sp = listSP.get(i);
                sp.setSoLuong(sp.getSoLuong() - soLuongMua);
                listSP.set(i, sp);
            }
        }
    }

    public void loadGioHang(ArrayList<HoaDon> listHD) {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã SP");
        defaultTableModel.addColumn("Tên SP");
        defaultTableModel.addColumn("Đơn vi tính");
        defaultTableModel.addColumn("Số lượng");
        defaultTableModel.addColumn("Giá ");
        defaultTableModel.addColumn("Thành tiền");
        for (HoaDon obj : listHD) {
            SanPham sp = new frmBanHang().getSPByCode(obj.getMaSP());
            Vector vector = new Vector();
            vector.add(obj.getMaSP());
            vector.add(sp.getTenSp());
            vector.add(sp.getDonViTinh());
            vector.add(formatter.format(obj.getSoLuong()));
            vector.add(formatter.format(obj.getDonGia()));
            vector.add(formatter.format(obj.getThanhTien()));
            defaultTableModel.addRow(vector);
        }
        tbl_gioHang.setModel(defaultTableModel);
        if (listHD.size() > 0) {
            btn_thanhToan.setEnabled(true);
        } else {
            btn_thanhToan.setEnabled(false);
        }
    }

    public SanPham getSPByCode(String maSP) {
        ArrayList<SanPham> listSP = loadSP();
        for (int i = 0; i < listSP.size(); i++) {
            if (maSP.equals(listSP.get(i).getMaSanPham())) {
                return listSP.get(i);
            }
        }
        return null;
    }

    int indexMaSPTrungTrongGioHang;

    public boolean checkSPExistGioHang(String maSP, ArrayList<HoaDon> listHD) {
        for (int i = 0; i < listHD.size(); i++) {
            if (maSP.equals(listHD.get(i).getMaSP())) {
                indexMaSPTrungTrongGioHang = i;
                return true;
            }
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_thanhToan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_maKH;
    private javax.swing.JLabel lbl_tenKH;
    private javax.swing.JLabel lbl_tongTien;
    private javax.swing.JTable tbl_gioHang;
    private javax.swing.JTable tbl_khachhang;
    private javax.swing.JTable tbl_sanpham;
    private javax.swing.JTextField txt_searchKH;
    private javax.swing.JTextField txt_searchSP;
    private javax.swing.JTextField txt_soLuong;
    // End of variables declaration//GEN-END:variables
}
