/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import OBJ.KhachHang;
import Utils.ktEmail;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.Reader;
import java.io.UnsupportedEncodingException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class frmKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form frmKhachHang
     */
    private DefaultTableModel defaultTableModel;
    ktEmail kt = new ktEmail();
    KhachHang kh = new KhachHang();
    ArrayList<KhachHang> listKH = new ArrayList<>();

    public frmKhachHang() {
        initComponents();
        loadFile();
        getData(listKH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_maKhachHang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_hoTenKH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_emailKH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_gioiTinhKH = new javax.swing.JComboBox<>();
        txt_trangThaiKH = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txt_sdtKH = new javax.swing.JTextField();
        txt_diaChiKH = new javax.swing.JTextField();
        err_sdt = new javax.swing.JLabel();
        err_email2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khachhang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        txt_timkiem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store-icon.png"))); // NOI18N
        jLabel1.setText("SIÊU THỊ MINI");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Users-Exit-icon.png"))); // NOI18N
        jButton5.setText("Thoát");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 50, 110, 29));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("|");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 80, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 50));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Mã KH:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txt_maKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_maKhachHangKeyPressed(evt);
            }
        });
        jPanel3.add(txt_maKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 220, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Họ tên:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        jPanel3.add(txt_hoTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 220, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Email:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txt_emailKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailKHtxt_emailActionPerformed(evt);
            }
        });
        txt_emailKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emailKHKeyPressed(evt);
            }
        });
        jPanel3.add(txt_emailKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 220, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("SĐT:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Địa chỉ:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Trạng thái:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, 30));

        txt_gioiTinhKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_gioiTinhKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jPanel3.add(txt_gioiTinhKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 140, 30));

        txt_trangThaiKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_trangThaiKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoạt động", "Đã khóa" }));
        jPanel3.add(txt_trangThaiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 140, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Giới tính:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 30));

        txt_sdtKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sdtKHActionPerformed(evt);
            }
        });
        txt_sdtKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sdtKHKeyPressed(evt);
            }
        });
        jPanel3.add(txt_sdtKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 220, 30));

        txt_diaChiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diaChiKHActionPerformed(evt);
            }
        });
        jPanel3.add(txt_diaChiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 220, 30));

        err_sdt.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        err_sdt.setForeground(new java.awt.Color(153, 0, 0));
        err_sdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                err_sdtKeyPressed(evt);
            }
        });
        jPanel3.add(err_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 230, 20));

        err_email2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        err_email2.setForeground(new java.awt.Color(153, 0, 0));
        err_email2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                err_email2KeyPressed(evt);
            }
        });
        jPanel3.add(err_email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 190, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setText("Xin mời nhập thông tin!");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 30));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bảng điều khiển", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_them.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-list-add-user-icon.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel4.add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 120, 30));

        btn_sua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 99, -1));

        btn_xoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Windows-Close-Program-icon.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, -1));

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reload-icon.png"))); // NOI18N
        btn_reset.setText("Cancel");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel4.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 120, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 310, 120));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 350, 580));

        tbl_khachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khachhangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_khachhang);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 1010, 510));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search-icon.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 50, 30));

        txt_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemActionPerformed(evt);
            }
        });
        jPanel2.add(txt_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 340, 30));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 500, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp3152222.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1920, 900));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_maKhachHangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_maKhachHangKeyPressed

    }//GEN-LAST:event_txt_maKhachHangKeyPressed

    private void txt_emailKHtxt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailKHtxt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailKHtxt_emailActionPerformed

    private void txt_emailKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKHKeyPressed
        // TODO add your handling code here:
            if (!kt.kiemTraEmail(txt_emailKH.getText())) {
                err_email2.setText("Email không đúng định dạng!!");
            } 
            else {
                err_email2.setText("");
            }
    }//GEN-LAST:event_txt_emailKHKeyPressed

    private void txt_sdtKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sdtKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sdtKHActionPerformed

    private void txt_sdtKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sdtKHKeyPressed
        // TODO add your handling code here:
//        if (kt.kiemTraSDT(txt_sdtKH.getText())) {
//            err_sdt.setText("không đúng định dạng!!");
//        } else {
//            err_sdt.setText("");
//        }
    }//GEN-LAST:event_txt_sdtKHKeyPressed

    private void txt_diaChiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diaChiKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diaChiKHActionPerformed

    private void err_sdtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_err_sdtKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_err_sdtKeyPressed

    private void err_email2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_err_email2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_err_email2KeyPressed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
       String maKH = txt_maKhachHang.getText();
        String tenKH = txt_hoTenKH.getText();
        String email = txt_emailKH.getText();
        String sdt = txt_sdtKH.getText();
        String diaChi = txt_diaChiKH.getText();
        String gioiTinh = "";
        if (txt_gioiTinhKH.getSelectedItem().equals("Nam")) {
            gioiTinh = "Nam";
        } else if (txt_gioiTinhKH.getSelectedItem().equals("Nữ")) {
            gioiTinh = "Nữ";
        } else {
            gioiTinh = "Khác";
        }
        int trangThai = 0;
        if (txt_trangThaiKH.getSelectedItem().toString().equals("Hoạt động")) {
            trangThai = 1;
        } else {
            trangThai = 0;
        }
        
        if (maKH.equals("") || email.equals("") || tenKH.equals("") || diaChi.equals("") || sdt.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhâp đủ thông tin!");
            return;
        }
        for (int i = 0; i < listKH.size(); i++) {
            if (maKH.equals(listKH.get(i).getMaKhachHang())) {
                JOptionPane.showMessageDialog(this, "Mã khách hàng bị trùng, vui lòng nhập lại!");
                return;
            }
        }
        if (!kt.kiemTraTen(tenKH)) {
            JOptionPane.showMessageDialog(this, "Tên không được có số!");
            return;
        }
        else if (kt.kiemTraEmail(email) != true) {
            JOptionPane.showMessageDialog(this, "Lỗi đinh dạng email!");
            return;
        }
        else if(kt.kiemTraSDT(sdt)){
            JOptionPane.showMessageDialog(this, "Lỗi định dạng số điện thoại!");
            return;
        }
        else {
            KhachHang kh = new KhachHang();
            kh.setMaKhachHang(maKH);
            kh.setEmail(email);
            kh.setGioiTinh(gioiTinh);
            kh.setHoTen(tenKH);
            kh.setSoDienThoai(sdt);
            kh.setDiaChi(diaChi);
            kh.setTrangThai(trangThai);
            listKH.add(kh);
            saveFile();
            getData(listKH);
            JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!");
            reset();
        }
    }//GEN-LAST:event_btn_themActionPerformed

     int index = -1;
    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        String tenNV = txt_hoTenKH.getText();
        String email = txt_emailKH.getText();
        String sdt = txt_sdtKH.getText();
        String diaChi = txt_diaChiKH.getText();
        String gioiTinh = "";
        if (txt_gioiTinhKH.getSelectedItem().equals("Nam")) {
            gioiTinh = "Nam";
        } else if (txt_gioiTinhKH.getSelectedItem().equals("Nữ")) {
            gioiTinh = "Nữ";
        } else {
            gioiTinh = "Khác";
        }
        
        int trangThai = 0;
        if (txt_trangThaiKH.getSelectedItem().toString().equals("Hoạt động")) {
            trangThai = 1;
        } else {
            trangThai = 0;
        }
        
        if (email.equals("") || tenNV.equals("") || diaChi.equals("") || sdt.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhâp đủ thông tin!");
            return;
        }
        
        else if (kt.kiemTraEmail(email) != true) {
            JOptionPane.showMessageDialog(this, "Lỗi đinh dạng email!");
            return;
        }
        else if (!kt.kiemTraTen(tenNV)) {
            JOptionPane.showMessageDialog(this, "Tên không được có số!");
            return;
        }
        else if(kt.kiemTraSDT(sdt)){
            JOptionPane.showMessageDialog(this, "Lỗi định dạng số điện thoại!");
            return;
        }

        kh.setEmail(email);
        kh.setGioiTinh(gioiTinh);
        kh.setHoTen(tenNV);
        kh.setSoDienThoai(sdt);
        kh.setDiaChi(diaChi);
        kh.setTrangThai(trangThai);
        listKH.set(index, kh);
        saveFile();
        getData(listKH);
        JOptionPane.showMessageDialog(this, "Sửa khách hàng thành công!");
        reset();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        Integer confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không ?", "XÓA", 2, 2);
        if (confirm == JOptionPane.YES_OPTION) {
            if (listKH.remove(kh)) {
                saveFile();
                getData(listKH);
                JOptionPane.showMessageDialog(this, "Xóa thành công khách hàng " + kh.getHoTen());
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        }
        reset();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tbl_khachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khachhangMouseClicked
        int row = tbl_khachhang.getSelectedRow();
        String maNV = tbl_khachhang.getValueAt(row, 0).toString();

        for (int i = 0; i < listKH.size(); i++) {
            if (maNV.equalsIgnoreCase(listKH.get(i).getMaKhachHang())) {
                kh = listKH.get(i);
                index = i;
                break;
            }
        }
        txt_maKhachHang.setEnabled(false);
        txt_maKhachHang.setText(kh.getMaKhachHang());
        txt_hoTenKH.setText(kh.getHoTen());
        txt_emailKH.setText(kh.getEmail());
        txt_sdtKH.setText(kh.getSoDienThoai());
        txt_diaChiKH.setText(kh.getDiaChi());

        if (kh.getGioiTinh().equals("Nam")) {
            txt_gioiTinhKH.setSelectedItem("Nam");
        } else if (kh.getGioiTinh().equals("Nữ")) {
            txt_gioiTinhKH.setSelectedItem("Nữ");
        } else {
            txt_gioiTinhKH.setSelectedItem("Khác");
        }

        if (kh.getTrangThai() == 1) {
            txt_trangThaiKH.setSelectedItem("Hoạt động");
        } else {
            txt_trangThaiKH.setSelectedItem("Đã khóa");
        }
        btn_them.setEnabled(false);
    }//GEN-LAST:event_tbl_khachhangMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String timKiem = txt_timkiem.getText();

        if (timKiem.equals("")) {
            getData(listKH);
        } else {
            ArrayList<KhachHang> listTimKiem = new ArrayList<>();
            for (int i = 0; i < listKH.size(); i++) {
                if (listKH.get(i).getMaKhachHang().contains(timKiem) || listKH.get(i).getSoDienThoai().contains(timKiem)) {
                    listTimKiem.add(listKH.get(i));
                }
            }
            getData(listTimKiem);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timkiemActionPerformed

    public void reset() {
        txt_emailKH.setText("");
        txt_maKhachHang.setText("");
        txt_hoTenKH.setText("");
        txt_diaChiKH.setText("");
        txt_sdtKH.setText("");
        txt_trangThaiKH.setSelectedIndex(0);
        txt_gioiTinhKH.setSelectedIndex(0);
        btn_them.setEnabled(true);
        btn_sua.setEnabled(true);
        btn_xoa.setEnabled(true);
        txt_maKhachHang.setEnabled(true);
        getData(listKH);
    }
    
    public void loadFile() {
        try {
            FileInputStream fileInputStream = new FileInputStream("khachhang.txt");
            Reader fr = new InputStreamReader(fileInputStream, "utf-8");
            BufferedReader br = new BufferedReader(fr);
            listKH = new ArrayList<>(); //lưu ý
            String s = null;

            try {
                while ((s = br.readLine()) != null) {
                    //Cắt chuỗi:
                    String arr[] = s.split("\t");
                    //Khởi tạo
                    KhachHang kh = new KhachHang();
                    kh.setMaKhachHang(arr[0]);
                    kh.setHoTen(arr[1]);
                    kh.setSoDienThoai(arr[2]);
                    kh.setEmail(arr[3]);
                    kh.setDiaChi(arr[4]);
                    kh.setGioiTinh(arr[5]);
                    kh.setTrangThai(Integer.parseInt(arr[6]));
                    listKH.add(kh);
                }
            } catch (IOException ex) {
                Logger.getLogger(frmKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(frmKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void saveFile() {
        try {
            FileOutputStream fileOutputStream = new FileOutputStream("khachhang.txt");
            Writer writer = new OutputStreamWriter(fileOutputStream, "utf-8"); //Khởi tạo
            BufferedWriter bw = new BufferedWriter(writer); //Khởi tạo
            String data = ""; //Tạo một string data bằng rỗng.
            
            for (int i = 0; i < listKH.size(); i++) {
                String row = ""; //tạo hàng rỗng
                row = row + listKH.get(i).getMaKhachHang() + "\t";
                row = row + listKH.get(i).getHoTen() + "\t";
                row = row + listKH.get(i).getSoDienThoai() + "\t";
                row = row + listKH.get(i).getEmail() + "\t";
                row = row + listKH.get(i).getDiaChi() + "\t";
                row = row + listKH.get(i).getGioiTinh() + "\t";
                row = row + listKH.get(i).getTrangThai() + "\n";
                data += row;
            }
            bw.write(data);
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(frmKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getData(ArrayList<KhachHang> listKH) {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã KH");
        defaultTableModel.addColumn("Họ tên KH");
        defaultTableModel.addColumn("Giới tính");
        defaultTableModel.addColumn("Email");
        defaultTableModel.addColumn("SĐT");
        defaultTableModel.addColumn("Địa Chỉ");
        defaultTableModel.addColumn("Trạng Thái");

        for (KhachHang obj : listKH) {
            Vector vector = new Vector();
            vector.add(obj.getMaKhachHang());
            vector.add(obj.getHoTen());
            vector.add(obj.getGioiTinh());
            vector.add(obj.getEmail());
            vector.add(obj.getSoDienThoai());
            vector.add(obj.getDiaChi());
            vector.add(obj.getTrangThai() == 1 ? "Hoạt động" : "Đã khóa");
            defaultTableModel.addRow(vector);
        }
        tbl_khachhang.setModel(defaultTableModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel err_email2;
    private javax.swing.JLabel err_sdt;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_khachhang;
    private javax.swing.JTextField txt_diaChiKH;
    private javax.swing.JTextField txt_emailKH;
    private javax.swing.JComboBox<String> txt_gioiTinhKH;
    private javax.swing.JTextField txt_hoTenKH;
    private javax.swing.JTextField txt_maKhachHang;
    private javax.swing.JTextField txt_sdtKH;
    private javax.swing.JTextField txt_timkiem;
    private javax.swing.JComboBox<String> txt_trangThaiKH;
    // End of variables declaration//GEN-END:variables
}
